### ISSUE TITLE
A fresh installation does not work?

### ISSUE THREAD

**Issue by andresmv** [rmariuzzo/markdown-swagger#1]
Just installed, seems broken?

$ markdown-swagger
/usr/local/lib/node_modules/markdown-swagger/index.js:21
const [source, target] = cli.input
      ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

**Comment by rmariuzzo** [comment]
What version of nodejs are you using?

**Comment by mickeybr** [comment]
Funny I was finally able to install in my project, but cannot seem to find the markdown-swagger executable anywhere.
```
$ npm markdown-swagger install
npm notice created a lockfile as package-lock.json. You should commit this file.
+ markdown-swagger@1.0.4
added 65 packages from 53 contributors and audited 97 packages in 5.162s
found 0 vulnerabilities
 
$ markdown-swagger
-bash: markdown-swagger: command not found
```

**Comment by KristieTom12** [comment]
@mickeybr try `npm install markdown-swagger -g`
